package com.ten.ParkNShop.mapper;

import com.ten.ParkNShop.entity.BackupHistory;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BackupHistoryMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backuphistory
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer backupid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backuphistory
     *
     * @mbggenerated
     */
    int insert(BackupHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backuphistory
     *
     * @mbggenerated
     */
    int insertSelective(BackupHistory record);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backuphistory
     *
     * @mbggenerated
     */
    BackupHistory selectByPrimaryKey(Integer backupid);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backuphistory
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BackupHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backuphistory
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BackupHistory record);

    List<BackupHistory> selectAllBackupHistory(@Param("start")int start,@Param("pageSize")int pageSize);


}