package com.ten.ParkNShop.mapper;

import com.ten.ParkNShop.entity.Buyer;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BuyerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer buyerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbggenerated
     */
    int insert(Buyer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbggenerated
     */
    int insertSelective(Buyer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbggenerated
     */
    Buyer selectByPrimaryKey(Integer buyerid);

    Buyer selectByBuyername(String buyername);

    int selectBuyerStatus(int buyerId);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Buyer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Buyer record);

    int updateBuyerStatusToNormal(int buyerId);

    int updateBuyerStatusToFrozen(int buyerId);

    int updateBuyerStatusToBlacklist(int buyerId);

    List<Buyer> selectAllNormalBuyer(@Param("start")int start,@Param("pageSize")int pageSize);
    List<Buyer> selectAllFrozenBuyer(@Param("start")int start,@Param("pageSize")int pageSize);
    List<Buyer> selectAllBlacklistBuyer(@Param("start")int start,@Param("pageSize")int pageSize);

}