package com.ten.ParkNShop.mapper;

import com.ten.ParkNShop.entity.Buyer;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BuyerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer buyerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbggenerated
     */
    int insert(Buyer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbggenerated
     */
    int insertSelective(Buyer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbggenerated
     */
    Buyer selectByPrimaryKey(Integer buyerId);

    Buyer selectBybuyerName(String buyerName);

    int selectbuyerStatus(int buyerId);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Buyer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Buyer record);

    int updatebuyerStatusToNormal(int buyerId);

    int updatebuyerStatusToFrozen(int buyerId);

    int updatebuyerStatusToBlacklist(int buyerId);

    int addBalance(@Param("buyerId")int buyerId,@Param("amount")float amount);

    List<Buyer> selectAllNormalBuyer(@Param("start")int start,@Param("pageSize")int pageSize);
    List<Buyer> selectAllFrozenBuyer(@Param("start")int start,@Param("pageSize")int pageSize);
    List<Buyer> selectAllBlacklistBuyer(@Param("start")int start,@Param("pageSize")int pageSize);

    int buyerRegister(Buyer buyer);
    Buyer findBuyer(@Param("buyerAccount") String buyerAccount,@Param("buyerPassword") String buyerPassword);

    int countAllBuyer();
}