package com.ten.ParkNShop.mapper;

import com.ten.ParkNShop.entity.Commission;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CommissionMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commission
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commission
     *
     * @mbggenerated
     */
    int insert(Commission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commission
     *
     * @mbggenerated
     */
    int insertSelective(Commission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commission
     *
     * @mbggenerated
     */
    Commission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commission
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Commission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commission
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Commission record);

    Commission selectLastCommission();

    int insertLast(@Param("commission")float commission, @Param("operatorAccount")String operatorAccount, @Param("time") java.sql.Date date);

    List<Commission> selectSomeCommission(@Param("start") int start, @Param("pageSize") int pageSize);
}