package com.ten.ParkNShop.mapper;

import com.ten.ParkNShop.entity.Order;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrderMapper {

    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated
     */
    int insertSelective(Order record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated
     */
    Order selectByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated
     */

    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Order record);

    /**
     * @Author tad
     * @Date created in 4:53 PM 12/15/2017
     * @Description 闁瀚ㄩ幍锟介張澶屾畱 Order 楠炴湹绮犵紒鎾寸亯闂嗗棔鑵戦幋顏勫絿 start 瀵拷婵娈� pageSize 娑擃亞绮ㄩ弸锟�
     *
     * @params [start, pageSize]
     * @return java.util.List<com.ten.ParkNShop.entity.Order>
     */
    List<Order> selectAllOrder(@Param("start") int start, @Param("pageSize")int pageSize);
    /**
     * @Author: tad
     * @Date: created in 11:04 AM 12/15/2017
     * @Description: 闁俺绻� buyerId 閺屻儲澹樼拠銉ф暏閹撮娈戞禒锟� start 瀵拷婵娈� pageSize 娑擄拷 Order
     *
     * @params [id, start, pageSize]
     * @return java.util.List<com.ten.ParkNShop.entity.Order>
     */
    List<Order> selectOrderBybuyerId(@Param("buyerId")int buyerId, @Param("start") int start, @Param("pageSize")int pageSize);

    /**
     * @Author: tad
     * @Date: created in 11:04 AM 12/15/2017
     * @Description: 闁俺绻� sellerId 閺屻儲澹樼拠銉ф暏閹撮娈戞禒锟� start 瀵拷婵娈� pageSize 娑擄拷 Order
     *
     * @params [id, start, pageSize]
     * @return java.util.List<com.ten.ParkNShop.entity.Order>
     */
    List<Order> selectOrderBysellerId(@Param("sellerId")int buyerId, @Param("start") int start, @Param("pageSize")int pageSize);

    /**
     * @Author: tad
     * @Date: created in 11:05 AM 12/15/2017
     * @Description: 闁俺绻� productId 閺屻儲澹樼拠銉ら獓閸濅胶娈戞禒锟� start 瀵拷婵娈� pageSize 娑擄拷 Order
     *
     * @params [id, start, pageSize]
     * @return java.util.List<com.ten.ParkNShop.entity.Order>
     */
    List<Order> selectOrderByproductId(@Param("productId")int buyerId, @Param("start") int start, @Param("pageSize")int pageSize);

	int countCompleted(@Param("sellerId")int sellerId);

	List<Order> findCompleted(@Param("sellerId")int sellerId,@Param("start") int start, @Param("pageSize")int pageSize);

	int countUncompleted(@Param("sellerId")int sellerId);

	List<Order> findUncompleted(@Param("sellerId")int sellerId, @Param("start") int start, @Param("pageSize")int pageSize);
}