package com.ten.ParkNShop.entity;

import java.util.Date;

public class AD {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad.ADId
     *
     * @mbggenerated
     */
    private Integer adId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad.ADType
     *
     * @mbggenerated
     */
    private Integer adType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad.ADStatus
     *
     * @mbggenerated
     */
    private Integer adStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad.otherId
     *
     * @mbggenerated
     */
    private Integer otherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad.adminId
     *
     * @mbggenerated
     */
    private Integer adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad.ADName
     *
     * @mbggenerated
     */
    private String adName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad.ADPhotoUrl
     *
     * @mbggenerated
     */
    private String adPhotoUrl;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad.ADDescription
     *
     * @mbggenerated
     */
    private String adDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad.ADPrice
     *
     * @mbggenerated
     */
    private Float adPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad.ADStartDate
     *
     * @mbggenerated
     */
    private Date adStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad.ADTime
     *
     * @mbggenerated
     */
    private Integer adTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad.ADId
     *
     * @return the value of ad.ADId
     *
     * @mbggenerated
     */
    public Integer getADId() {
        return adId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad.ADId
     *
     * @param adId the value for ad.ADId
     *
     * @mbggenerated
     */
    public void setADId(Integer adId) {
        this.adId = adId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad.ADType
     *
     * @return the value of ad.ADType
     *
     * @mbggenerated
     */
    public Integer getADType() {
        return adType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad.ADType
     *
     * @param adType the value for ad.ADType
     *
     * @mbggenerated
     */
    public void setADType(Integer adType) {
        this.adType = adType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad.ADStatus
     *
     * @return the value of ad.ADStatus
     *
     * @mbggenerated
     */
    public Integer getADStatus() {
        return adStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad.ADStatus
     *
     * @param adStatus the value for ad.ADStatus
     *
     * @mbggenerated
     */
    public void setADStatus(Integer adStatus) {
        this.adStatus = adStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad.otherId
     *
     * @return the value of ad.otherId
     *
     * @mbggenerated
     */
    public Integer getOtherId() {
        return otherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad.otherId
     *
     * @param otherId the value for ad.otherId
     *
     * @mbggenerated
     */
    public void setOtherId(Integer otherId) {
        this.otherId = otherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad.adminId
     *
     * @return the value of ad.adminId
     *
     * @mbggenerated
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad.adminId
     *
     * @param adminId the value for ad.adminId
     *
     * @mbggenerated
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad.ADName
     *
     * @return the value of ad.ADName
     *
     * @mbggenerated
     */
    public String getADName() {
        return adName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad.ADName
     *
     * @param adName the value for ad.ADName
     *
     * @mbggenerated
     */
    public void setADName(String adName) {
        this.adName = adName == null ? null : adName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad.ADPhotoUrl
     *
     * @return the value of ad.ADPhotoUrl
     *
     * @mbggenerated
     */
    public String getADPhotoUrl() {
        return adPhotoUrl;
    }

    public void setADPhotoUrl(String adPhotoUrl) {
        this.adPhotoUrl = adPhotoUrl == null ? null : adPhotoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad.ADDescription
     *
     * @return the value of ad.ADDescription
     *
     * @mbggenerated
     */
    public String getADDescription() {
        return adDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad.ADDescription
     *
     * @param adDescription the value for ad.ADDescription
     *
     * @mbggenerated
     */
    public void setADDescription(String adDescription) {
        this.adDescription = adDescription == null ? null : adDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad.ADPrice
     *
     * @return the value of ad.ADPrice
     *
     * @mbggenerated
     */
    public Float getADPrice() {
        return adPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad.ADPrice
     *
     * @param adPrice the value for ad.ADPrice
     *
     * @mbggenerated
     */
    public void setADPrice(Float adPrice) {
        this.adPrice = adPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad.ADStartDate
     *
     * @return the value of ad.ADStartDate
     *
     * @mbggenerated
     */
    public Date getADStartDate() {
        return adStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad.ADStartDate
     *
     * @param adStartDate the value for ad.ADStartDate
     *
     * @mbggenerated
     */
    public void setADStartDate(Date adStartDate) {
        this.adStartDate = adStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad.ADTime
     *
     * @return the value of ad.ADTime
     *
     * @mbggenerated
     */
    public Integer getADTime() {
        return adTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad.ADTime
     *
     * @param adTime the value for ad.ADTime
     *
     * @mbggenerated
     */
    public void setADTime(Integer adTime) {
        this.adTime = adTime;
    }
}