package com.ten.ParkNShop.entity;

import java.util.Date;

public class AD {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad.adId
     *
     * 
     */
    private Integer adId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad.adType
     *
     * 
     */
    private String adType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad.adStatus
     *
     * 
     */
    private String adStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad.sellerId
     *
     * 
     */
    private Integer sellerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad.adminId
     *
     * 
     */
    private Integer adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad.adName
     *
     * 
     */
    private String adName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad.adPhotoUrl
     *
     * 
     */
    private String adPhotoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad.adClickUrl
     *
     * 
     */
    private String adClickUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad.adDescription
     *
     * 
     */
    private String adDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad.adPrice
     *
     * 
     */
    private Float adPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad.adStartDate
     *
     * 
     */
    private Date adStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad.adTime
     *
     * 
     */
    private Integer adTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad.adId
     *
     * @return the value of ad.adId
     *
     * 
     */
    public Integer getADId() {
        return adId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad.adId
     *
     * @param adId the value for ad.adId
     *
     * 
     */
    public void setADId(Integer adId) {
        this.adId = adId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad.adType
     *
     * @return the value of ad.adType
     *
     * 
     */
    public String getADType() {
        return adType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad.adType
     *
     * @param adType the value for ad.adType
     *
     * 
     */
    public void setADType(String adType) {
        this.adType = adType == null ? null : adType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad.adStatus
     *
     * @return the value of ad.adStatus
     *
     * 
     */
    public String getADStatus() {
        return adStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad.adStatus
     *
     * @param adStatus the value for ad.adStatus
     *
     * 
     */
    public void setADStatus(String adStatus) {
        this.adStatus = adStatus == null ? null : adStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad.sellerId
     *
     * @return the value of ad.sellerId
     *
     * 
     */
    public Integer getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad.sellerId
     *
     * @param sellerId the value for ad.sellerId
     *
     * 
     */
    public void setSellerId(Integer sellerId) {
        this.sellerId = sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad.adminId
     *
     * @return the value of ad.adminId
     *
     * 
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad.adminId
     *
     * @param adminId the value for ad.adminId
     *
     * 
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad.adName
     *
     * @return the value of ad.adName
     *
     * 
     */
    public String getADName() {
        return adName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad.adName
     *
     * @param adName the value for ad.adName
     *
     * 
     */
    public void setADName(String adName) {
        this.adName = adName == null ? null : adName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad.adPhotoUrl
     *
     * @return the value of ad.adPhotoUrl
     *
     * 
     */
    public String getADPhotoUrl() {
        return adPhotoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad.adPhotoUrl
     *
     * @param adPhotoUrl the value for ad.adPhotoUrl
     *
     * 
     */
    public void setADPhotoUrl(String adPhotoUrl) {
        this.adPhotoUrl = adPhotoUrl == null ? null : adPhotoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad.adClickUrl
     *
     * @return the value of ad.adClickUrl
     *
     * 
     */
    public String getADClickUrl() {
        return adClickUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad.adClickUrl
     *
     * @param adClickUrl the value for ad.adClickUrl
     *
     * 
     */
    public void setADClickUrl(String adClickUrl) {
        this.adClickUrl = adClickUrl == null ? null : adClickUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad.adDescription
     *
     * @return the value of ad.adDescription
     *
     * 
     */
    public String getADDescription() {
        return adDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad.adDescription
     *
     * @param adDescription the value for ad.adDescription
     *
     * 
     */
    public void setADDescription(String adDescription) {
        this.adDescription = adDescription == null ? null : adDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad.adPrice
     *
     * @return the value of ad.adPrice
     *
     * 
     */
    public Float getADPrice() {
        return adPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad.adPrice
     *
     * @param adPrice the value for ad.adPrice
     *
     * 
     */
    public void setADPrice(Float adPrice) {
        this.adPrice = adPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad.adStartDate
     *
     * @return the value of ad.adStartDate
     *
     * 
     */
    public Date getADStartDate() {
        return adStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad.adStartDate
     *
     * @param adStartDate the value for ad.adStartDate
     *
     * 
     */
    public void setADStartDate(Date adStartDate) {
        this.adStartDate = adStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad.adTime
     *
     * @return the value of ad.adTime
     *
     * 
     */
    public Integer getADTime() {
        return adTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad.adTime
     *
     * @param adTime the value for ad.adTime
     *
     * 
     */
    public void setADTime(Integer adTime) {
        this.adTime = adTime;
    }
}