package com.ten.ParkNShop.entity;

public class Admin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.adminId
     *
     * @mbggenerated
     */
    private Integer adminid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.adminAccount
     *
     * @mbggenerated
     */
    private String adminaccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.adminPassword
     *
     * @mbggenerated
     */
    private String adminpassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.adminName
     *
     * @mbggenerated
     */
    private String adminname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.adminBalance
     *
     * @mbggenerated
     */
    private Float adminbalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.adminPhone
     *
     * @mbggenerated
     */
    private String adminphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.adminStatus
     *
     * @mbggenerated
     */
    private Integer adminstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.adminId
     *
     * @return the value of admins.adminId
     *
     * @mbggenerated
     */
    public Integer getAdminid() {
        return adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.adminId
     *
     * @param adminid the value for admins.adminId
     *
     * @mbggenerated
     */
    public void setAdminid(Integer adminid) {
        this.adminid = adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.adminAccount
     *
     * @return the value of admins.adminAccount
     *
     * @mbggenerated
     */
    public String getAdminaccount() {
        return adminaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.adminAccount
     *
     * @param adminaccount the value for admins.adminAccount
     *
     * @mbggenerated
     */
    public void setAdminaccount(String adminaccount) {
        this.adminaccount = adminaccount == null ? null : adminaccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.adminPassword
     *
     * @return the value of admins.adminPassword
     *
     * @mbggenerated
     */
    public String getAdminpassword() {
        return adminpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.adminPassword
     *
     * @param adminpassword the value for admins.adminPassword
     *
     * @mbggenerated
     */
    public void setAdminpassword(String adminpassword) {
        this.adminpassword = adminpassword == null ? null : adminpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.adminName
     *
     * @return the value of admins.adminName
     *
     * @mbggenerated
     */
    public String getAdminname() {
        return adminname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.adminName
     *
     * @param adminname the value for admins.adminName
     *
     * @mbggenerated
     */
    public void setAdminname(String adminname) {
        this.adminname = adminname == null ? null : adminname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.adminBalance
     *
     * @return the value of admins.adminBalance
     *
     * @mbggenerated
     */
    public Float getAdminbalance() {
        return adminbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.adminBalance
     *
     * @param adminbalance the value for admins.adminBalance
     *
     * @mbggenerated
     */
    public void setAdminbalance(Float adminbalance) {
        this.adminbalance = adminbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.adminPhone
     *
     * @return the value of admins.adminPhone
     *
     * @mbggenerated
     */
    public String getAdminphone() {
        return adminphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.adminPhone
     *
     * @param adminphone the value for admins.adminPhone
     *
     * @mbggenerated
     */
    public void setAdminphone(String adminphone) {
        this.adminphone = adminphone == null ? null : adminphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.adminStatus
     *
     * @return the value of admins.adminStatus
     *
     * @mbggenerated
     */
    public Integer getAdminstatus() {
        return adminstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.adminStatus
     *
     * @param adminstatus the value for admins.adminStatus
     *
     * @mbggenerated
     */
    public void setAdminstatus(Integer adminstatus) {
        this.adminstatus = adminstatus;
    }
}