package com.ten.ParkNShop.entity;

import java.util.Date;

public class BackupHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backuphistory.backupId
     *
     * @mbggenerated
     */
    private Integer backupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backuphistory.backupAccount
     *
     * @mbggenerated
     */
    private String backupaccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backuphistory.backupDate
     *
     * @mbggenerated
     */
    private Date backupdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backuphistory.backupFilePath
     *
     * @mbggenerated
     */
    private String backupfilepath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backuphistory.backupId
     *
     * @return the value of backuphistory.backupId
     *
     * @mbggenerated
     */
    public Integer getBackupid() {
        return backupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backuphistory.backupId
     *
     * @param backupid the value for backuphistory.backupId
     *
     * @mbggenerated
     */
    public void setBackupid(Integer backupid) {
        this.backupid = backupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backuphistory.backupAccount
     *
     * @return the value of backuphistory.backupAccount
     *
     * @mbggenerated
     */
    public String getBackupaccount() {
        return backupaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backuphistory.backupAccount
     *
     * @param backupaccount the value for backuphistory.backupAccount
     *
     * @mbggenerated
     */
    public void setBackupaccount(String backupaccount) {
        this.backupaccount = backupaccount == null ? null : backupaccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backuphistory.backupDate
     *
     * @return the value of backuphistory.backupDate
     *
     * @mbggenerated
     */
    public Date getBackupdate() {
        return backupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backuphistory.backupDate
     *
     * @param backupdate the value for backuphistory.backupDate
     *
     * @mbggenerated
     */
    public void setBackupdate(Date backupdate) {
        this.backupdate = backupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backuphistory.backupFilePath
     *
     * @return the value of backuphistory.backupFilePath
     *
     * @mbggenerated
     */
    public String getBackupfilepath() {
        return backupfilepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backuphistory.backupFilePath
     *
     * @param backupfilepath the value for backuphistory.backupFilePath
     *
     * @mbggenerated
     */
    public void setBackupfilepath(String backupfilepath) {
        this.backupfilepath = backupfilepath == null ? null : backupfilepath.trim();
    }
}