package com.ten.ParkNShop.entity;

public class Buyer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer.buyerId
     *
     * @mbggenerated
     */
    private Integer buyerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer.buyerName
     *
     * @mbggenerated
     */
    private String buyername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer.buyerAddress
     *
     * @mbggenerated
     */
    private String buyeraddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer.buyerPhone
     *
     * @mbggenerated
     */
    private String buyerphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer.buyerPassword
     *
     * @mbggenerated
     */
    private String buyerpassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer.buyerStatus
     *
     * @mbggenerated
     */
    private Integer buyerstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer.buyerBalance
     *
     * @mbggenerated
     */
    private Float buyerbalance;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer.buyerId
     *
     * @return the value of buyer.buyerId
     *
     * @mbggenerated
     */
    public Integer getBuyerid() {
        return buyerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer.buyerId
     *
     * @param buyerid the value for buyer.buyerId
     *
     * @mbggenerated
     */
    public void setBuyerid(Integer buyerid) {
        this.buyerid = buyerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer.buyerName
     *
     * @return the value of buyer.buyerName
     *
     * @mbggenerated
     */
    public String getBuyername() {
        return buyername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer.buyerName
     *
     * @param buyername the value for buyer.buyerName
     *
     * @mbggenerated
     */
    public void setBuyername(String buyername) {
        this.buyername = buyername == null ? null : buyername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer.buyerAddress
     *
     * @return the value of buyer.buyerAddress
     *
     * @mbggenerated
     */
    public String getBuyeraddress() {
        return buyeraddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer.buyerAddress
     *
     * @param buyeraddress the value for buyer.buyerAddress
     *
     * @mbggenerated
     */
    public void setBuyeraddress(String buyeraddress) {
        this.buyeraddress = buyeraddress == null ? null : buyeraddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer.buyerPhone
     *
     * @return the value of buyer.buyerPhone
     *
     * @mbggenerated
     */
    public String getBuyerphone() {
        return buyerphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer.buyerPhone
     *
     * @param buyerphone the value for buyer.buyerPhone
     *
     * @mbggenerated
     */
    public void setBuyerphone(String buyerphone) {
        this.buyerphone = buyerphone == null ? null : buyerphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer.buyerPassword
     *
     * @return the value of buyer.buyerPassword
     *
     * @mbggenerated
     */
    public String getBuyerpassword() {
        return buyerpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer.buyerPassword
     *
     * @param buyerpassword the value for buyer.buyerPassword
     *
     * @mbggenerated
     */
    public void setBuyerpassword(String buyerpassword) {
        this.buyerpassword = buyerpassword == null ? null : buyerpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer.buyerStatus
     *
     * @return the value of buyer.buyerStatus
     *
     * @mbggenerated
     */
    public Integer getBuyerstatus() {
        return buyerstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer.buyerStatus
     *
     * @param buyerstatus the value for buyer.buyerStatus
     *
     * @mbggenerated
     */
    public void setBuyerstatus(Integer buyerstatus) {
        this.buyerstatus = buyerstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer.buyerBalance
     *
     * @return the value of buyer.buyerBalance
     *
     * @mbggenerated
     */
    public Float getBuyerbalance() {
        return buyerbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer.buyerBalance
     *
     * @param buyerbalance the value for buyer.buyerBalance
     *
     * @mbggenerated
     */
    public void setBuyerbalance(Float buyerbalance) {
        this.buyerbalance = buyerbalance;
    }
}