package com.ten.ParkNShop.entity;

public class Buyer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Buyer.buyerId
     *
     * @mbggenerated
     */
    private Integer buyerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Buyer.buyerName
     *
     * @mbggenerated
     */
    private String buyerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Buyer.buyerAddress
     *
     * @mbggenerated
     */
    private String buyerAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Buyer.buyerPhone
     *
     * @mbggenerated
     */
    private String buyerPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Buyer.buyerPassword
     *
     * @mbggenerated
     */
    private String buyerPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Buyer.buyerStatus
     *
     * @mbggenerated
     */
    private Integer buyerStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Buyer.buyerBalance
     *
     * @mbggenerated
     */
    private Float buyerBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Buyer.buyerAccount
     *
     * @mbggenerated
     */
    private String buyerAccount;

    public Integer getbuyerId() {
        return buyerId;
    }

    public void setbuyerId(Integer buyerId) {
        this.buyerId = buyerId;
    }

    public String getbuyerName() {
        return buyerName;
    }

    public void setbuyerName(String buyerName) {
        this.buyerName = buyerName;
    }

    public String getbuyerAddress() {
        return buyerAddress;
    }

    public void setbuyerAddress(String buyerAddress) {
        this.buyerAddress = buyerAddress;
    }

    public String getbuyerPhone() {
        return buyerPhone;
    }

    public void setbuyerPhone(String buyerPhone) {
        this.buyerPhone = buyerPhone;
    }

    public String getbuyerPassword() {
        return buyerPassword;
    }

    public void setbuyerPassword(String buyerPassword) {
        this.buyerPassword = buyerPassword;
    }

    public Integer getbuyerStatus() {
        return buyerStatus;
    }

    public void setbuyerStatus(Integer buyerStatus) {
        this.buyerStatus = buyerStatus;
    }

    public Float getbuyerBalance() {
        return buyerBalance;
    }

    public void setbuyerBalance(Float buyerBalance) {
        this.buyerBalance = buyerBalance;
    }

    public String getbuyerAccount() {
        return buyerAccount;
    }

    public void setbuyerAccount(String buyerAccount) {
        this.buyerAccount = buyerAccount;
    }

    @Override
    public String toString() {
        return "Buyer{" +
                "buyerId=" + buyerId +
                ", buyerName='" + buyerName + '\'' +
                ", buyerAddress='" + buyerAddress + '\'' +
                ", buyerPhone='" + buyerPhone + '\'' +
                ", buyerPassword='" + buyerPassword + '\'' +
                ", buyerStatus=" + buyerStatus +
                ", buyerBalance=" + buyerBalance +
                ", buyerAccount='" + buyerAccount + '\'' +
                '}';
    }
}