package com.ten.ParkNShop.entity;

import java.util.Date;

public class Commission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission.commission
     *
     * @mbggenerated
     */
    private Float commission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission.operatorAccount
     *
     * @mbggenerated
     */
    private String operatorAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission.id
     *
     * @return the value of commission.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission.id
     *
     * @param id the value for commission.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission.commission
     *
     * @return the value of commission.commission
     *
     * @mbggenerated
     */
    public Float getCommission() {
        return commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission.commission
     *
     * @param commission the value for commission.commission
     *
     * @mbggenerated
     */
    public void setCommission(Float commission) {
        this.commission = commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission.operatorAccount
     *
     * @return the value of commission.operatorAccount
     *
     * @mbggenerated
     */
    public String getoperatorAccount() {
        return operatorAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission.operatorAccount
     *
     * @param operatorAccount the value for commission.operatorAccount
     *
     * @mbggenerated
     */
    public void setoperatorAccount(String operatorAccount) {
        this.operatorAccount = operatorAccount == null ? null : operatorAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission.time
     *
     * @return the value of commission.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission.time
     *
     * @param time the value for commission.time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }
}