package com.ten.ParkNShop.mapper;

import com.ten.ParkNShop.entity.Buyer;

import java.util.List;

import com.ten.ParkNShop.entity.BuyerExample;
import com.ten.ParkNShop.entity.Seller;
import org.apache.ibatis.annotations.Param;

public interface BuyerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Buyer
     *
     * @mbggenerated
     */
    Buyer selectBuyerByAccount(String account);
    int countByExample(BuyerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Buyer
     *
     * @mbggenerated
     */
    int deleteByExample(BuyerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Buyer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer buyerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Buyer
     *
     * @mbggenerated
     */
    int insert(Buyer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Buyer
     *
     * @mbggenerated
     */
    int insertSelective(Buyer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Buyer
     *
     * @mbggenerated
     */
    List<Buyer> selectByExample(BuyerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Buyer
     *
     * @mbggenerated
     */
    Buyer selectByPrimaryKey(Integer buyerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Buyer
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Buyer record, @Param("example") BuyerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Buyer
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Buyer record, @Param("example") BuyerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Buyer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Buyer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Buyer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Buyer record);
    int buyerRegister(Buyer buyer);
    Buyer findBuyer(@Param("buyerAccount") String buyerAccount,@Param("buyerPassword") String buyerPassword);
}