package com.ten.ParkNShop.entity;

public class Buyer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Buyer.buyerId
     *
     * @mbggenerated
     */
    private Integer buyerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Buyer.buyerName
     *
     * @mbggenerated
     */
    private String buyerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Buyer.buyerAddress
     *
     * @mbggenerated
     */
    private String buyerAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Buyer.buyerPhone
     *
     * @mbggenerated
     */
    private String buyerPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Buyer.buyerPassword
     *
     * @mbggenerated
     */
    private String buyerPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Buyer.buyerStatus
     *
     * @mbggenerated
     */
    private Integer buyerStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Buyer.buyerBalance
     *
     * @mbggenerated
     */
    private Float buyerBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Buyer.buyerAccount
     *
     * @mbggenerated
     */
    private String buyerAccount;

    public Integer getBuyerId() {
        return buyerId;
    }

    public void setBuyerId(Integer buyerId) {
        this.buyerId = buyerId;
    }

    public String getBuyerName() {
        return buyerName;
    }

    public void setBuyerName(String buyerName) {
        this.buyerName = buyerName;
    }

    public String getBuyerAddress() {
        return buyerAddress;
    }

    public void setBuyerAddress(String buyerAddress) {
        this.buyerAddress = buyerAddress;
    }

    public String getBuyerPhone() {
        return buyerPhone;
    }

    public void setBuyerPhone(String buyerPhone) {
        this.buyerPhone = buyerPhone;
    }

    public String getBuyerPassword() {
        return buyerPassword;
    }

    public void setBuyerPassword(String buyerPassword) {
        this.buyerPassword = buyerPassword;
    }

    public Integer getBuyerStatus() {
        return buyerStatus;
    }

    public void setBuyerStatus(Integer buyerStatus) {
        this.buyerStatus = buyerStatus;
    }

    public Float getBuyerBalance() {
        return buyerBalance;
    }

    public void setBuyerBalance(Float buyerBalance) {
        this.buyerBalance = buyerBalance;
    }

    public String getBuyerAccount() {
        return buyerAccount;
    }

    public void setBuyerAccount(String buyerAccount) {
        this.buyerAccount = buyerAccount;
    }
}