package com.ten.ParkNShop.entity;

import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orderId
     *
     * @mbggenerated
     */
    private Integer orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.sellerId
     *
     * @mbggenerated
     */
    private Integer sellerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.buyerId
     *
     * @mbggenerated
     */
    private Integer buyerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.productId
     *
     * @mbggenerated
     */
    private Integer productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.count
     *
     * @mbggenerated
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.totalPrice
     *
     * @mbggenerated
     */
    private Float totalprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orderStatus
     *
     * @mbggenerated
     */
    private Integer orderstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orderTime
     *
     * @mbggenerated
     */
    private Date ordertime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orderId
     *
     * @return the value of orders.orderId
     *
     * @mbggenerated
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orderId
     *
     * @param orderid the value for orders.orderId
     *
     * @mbggenerated
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.sellerId
     *
     * @return the value of orders.sellerId
     *
     * @mbggenerated
     */
    public Integer getSellerid() {
        return sellerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.sellerId
     *
     * @param sellerid the value for orders.sellerId
     *
     * @mbggenerated
     */
    public void setSellerid(Integer sellerid) {
        this.sellerid = sellerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.buyerId
     *
     * @return the value of orders.buyerId
     *
     * @mbggenerated
     */
    public Integer getBuyerid() {
        return buyerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.buyerId
     *
     * @param buyerid the value for orders.buyerId
     *
     * @mbggenerated
     */
    public void setBuyerid(Integer buyerid) {
        this.buyerid = buyerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.productId
     *
     * @return the value of orders.productId
     *
     * @mbggenerated
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.productId
     *
     * @param productid the value for orders.productId
     *
     * @mbggenerated
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.count
     *
     * @return the value of orders.count
     *
     * @mbggenerated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.count
     *
     * @param count the value for orders.count
     *
     * @mbggenerated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.totalPrice
     *
     * @return the value of orders.totalPrice
     *
     * @mbggenerated
     */
    public Float getTotalprice() {
        return totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.totalPrice
     *
     * @param totalprice the value for orders.totalPrice
     *
     * @mbggenerated
     */
    public void setTotalprice(Float totalprice) {
        this.totalprice = totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.address
     *
     * @return the value of orders.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.address
     *
     * @param address the value for orders.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orderStatus
     *
     * @return the value of orders.orderStatus
     *
     * @mbggenerated
     */
    public Integer getOrderstatus() {
        return orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orderStatus
     *
     * @param orderstatus the value for orders.orderStatus
     *
     * @mbggenerated
     */
    public void setOrderstatus(Integer orderstatus) {
        this.orderstatus = orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orderTime
     *
     * @return the value of orders.orderTime
     *
     * @mbggenerated
     */
    public Date getOrdertime() {
        return ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orderTime
     *
     * @param ordertime the value for orders.orderTime
     *
     * @mbggenerated
     */
    public void setOrdertime(Date ordertime) {
        this.ordertime = ordertime;
    }
}