package com.ten.ParkNShop.entity;

import java.util.ArrayList;
import java.util.List;

public class BuyerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Buyer
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Buyer
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Buyer
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Buyer
     *
     * @mbggenerated
     */
    public BuyerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Buyer
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Buyer
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Buyer
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Buyer
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Buyer
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Buyer
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Buyer
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Buyer
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Buyer
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Buyer
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Buyer
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBuyeridIsNull() {
            addCriterion("buyerId is null");
            return (Criteria) this;
        }

        public Criteria andBuyeridIsNotNull() {
            addCriterion("buyerId is not null");
            return (Criteria) this;
        }

        public Criteria andBuyeridEqualTo(Integer value) {
            addCriterion("buyerId =", value, "buyerid");
            return (Criteria) this;
        }

        public Criteria andBuyeridNotEqualTo(Integer value) {
            addCriterion("buyerId <>", value, "buyerid");
            return (Criteria) this;
        }

        public Criteria andBuyeridGreaterThan(Integer value) {
            addCriterion("buyerId >", value, "buyerid");
            return (Criteria) this;
        }

        public Criteria andBuyeridGreaterThanOrEqualTo(Integer value) {
            addCriterion("buyerId >=", value, "buyerid");
            return (Criteria) this;
        }

        public Criteria andBuyeridLessThan(Integer value) {
            addCriterion("buyerId <", value, "buyerid");
            return (Criteria) this;
        }

        public Criteria andBuyeridLessThanOrEqualTo(Integer value) {
            addCriterion("buyerId <=", value, "buyerid");
            return (Criteria) this;
        }

        public Criteria andBuyeridIn(List<Integer> values) {
            addCriterion("buyerId in", values, "buyerid");
            return (Criteria) this;
        }

        public Criteria andBuyeridNotIn(List<Integer> values) {
            addCriterion("buyerId not in", values, "buyerid");
            return (Criteria) this;
        }

        public Criteria andBuyeridBetween(Integer value1, Integer value2) {
            addCriterion("buyerId between", value1, value2, "buyerid");
            return (Criteria) this;
        }

        public Criteria andBuyeridNotBetween(Integer value1, Integer value2) {
            addCriterion("buyerId not between", value1, value2, "buyerid");
            return (Criteria) this;
        }

        public Criteria andBuyernameIsNull() {
            addCriterion("buyerName is null");
            return (Criteria) this;
        }

        public Criteria andBuyernameIsNotNull() {
            addCriterion("buyerName is not null");
            return (Criteria) this;
        }

        public Criteria andBuyernameEqualTo(String value) {
            addCriterion("buyerName =", value, "buyername");
            return (Criteria) this;
        }

        public Criteria andBuyernameNotEqualTo(String value) {
            addCriterion("buyerName <>", value, "buyername");
            return (Criteria) this;
        }

        public Criteria andBuyernameGreaterThan(String value) {
            addCriterion("buyerName >", value, "buyername");
            return (Criteria) this;
        }

        public Criteria andBuyernameGreaterThanOrEqualTo(String value) {
            addCriterion("buyerName >=", value, "buyername");
            return (Criteria) this;
        }

        public Criteria andBuyernameLessThan(String value) {
            addCriterion("buyerName <", value, "buyername");
            return (Criteria) this;
        }

        public Criteria andBuyernameLessThanOrEqualTo(String value) {
            addCriterion("buyerName <=", value, "buyername");
            return (Criteria) this;
        }

        public Criteria andBuyernameLike(String value) {
            addCriterion("buyerName like", value, "buyername");
            return (Criteria) this;
        }

        public Criteria andBuyernameNotLike(String value) {
            addCriterion("buyerName not like", value, "buyername");
            return (Criteria) this;
        }

        public Criteria andBuyernameIn(List<String> values) {
            addCriterion("buyerName in", values, "buyername");
            return (Criteria) this;
        }

        public Criteria andBuyernameNotIn(List<String> values) {
            addCriterion("buyerName not in", values, "buyername");
            return (Criteria) this;
        }

        public Criteria andBuyernameBetween(String value1, String value2) {
            addCriterion("buyerName between", value1, value2, "buyername");
            return (Criteria) this;
        }

        public Criteria andBuyernameNotBetween(String value1, String value2) {
            addCriterion("buyerName not between", value1, value2, "buyername");
            return (Criteria) this;
        }

        public Criteria andBuyeraddressIsNull() {
            addCriterion("buyerAddress is null");
            return (Criteria) this;
        }

        public Criteria andBuyeraddressIsNotNull() {
            addCriterion("buyerAddress is not null");
            return (Criteria) this;
        }

        public Criteria andBuyeraddressEqualTo(String value) {
            addCriterion("buyerAddress =", value, "buyeraddress");
            return (Criteria) this;
        }

        public Criteria andBuyeraddressNotEqualTo(String value) {
            addCriterion("buyerAddress <>", value, "buyeraddress");
            return (Criteria) this;
        }

        public Criteria andBuyeraddressGreaterThan(String value) {
            addCriterion("buyerAddress >", value, "buyeraddress");
            return (Criteria) this;
        }

        public Criteria andBuyeraddressGreaterThanOrEqualTo(String value) {
            addCriterion("buyerAddress >=", value, "buyeraddress");
            return (Criteria) this;
        }

        public Criteria andBuyeraddressLessThan(String value) {
            addCriterion("buyerAddress <", value, "buyeraddress");
            return (Criteria) this;
        }

        public Criteria andBuyeraddressLessThanOrEqualTo(String value) {
            addCriterion("buyerAddress <=", value, "buyeraddress");
            return (Criteria) this;
        }

        public Criteria andBuyeraddressLike(String value) {
            addCriterion("buyerAddress like", value, "buyeraddress");
            return (Criteria) this;
        }

        public Criteria andBuyeraddressNotLike(String value) {
            addCriterion("buyerAddress not like", value, "buyeraddress");
            return (Criteria) this;
        }

        public Criteria andBuyeraddressIn(List<String> values) {
            addCriterion("buyerAddress in", values, "buyeraddress");
            return (Criteria) this;
        }

        public Criteria andBuyeraddressNotIn(List<String> values) {
            addCriterion("buyerAddress not in", values, "buyeraddress");
            return (Criteria) this;
        }

        public Criteria andBuyeraddressBetween(String value1, String value2) {
            addCriterion("buyerAddress between", value1, value2, "buyeraddress");
            return (Criteria) this;
        }

        public Criteria andBuyeraddressNotBetween(String value1, String value2) {
            addCriterion("buyerAddress not between", value1, value2, "buyeraddress");
            return (Criteria) this;
        }

        public Criteria andBuyerphoneIsNull() {
            addCriterion("buyerPhone is null");
            return (Criteria) this;
        }

        public Criteria andBuyerphoneIsNotNull() {
            addCriterion("buyerPhone is not null");
            return (Criteria) this;
        }

        public Criteria andBuyerphoneEqualTo(String value) {
            addCriterion("buyerPhone =", value, "buyerphone");
            return (Criteria) this;
        }

        public Criteria andBuyerphoneNotEqualTo(String value) {
            addCriterion("buyerPhone <>", value, "buyerphone");
            return (Criteria) this;
        }

        public Criteria andBuyerphoneGreaterThan(String value) {
            addCriterion("buyerPhone >", value, "buyerphone");
            return (Criteria) this;
        }

        public Criteria andBuyerphoneGreaterThanOrEqualTo(String value) {
            addCriterion("buyerPhone >=", value, "buyerphone");
            return (Criteria) this;
        }

        public Criteria andBuyerphoneLessThan(String value) {
            addCriterion("buyerPhone <", value, "buyerphone");
            return (Criteria) this;
        }

        public Criteria andBuyerphoneLessThanOrEqualTo(String value) {
            addCriterion("buyerPhone <=", value, "buyerphone");
            return (Criteria) this;
        }

        public Criteria andBuyerphoneLike(String value) {
            addCriterion("buyerPhone like", value, "buyerphone");
            return (Criteria) this;
        }

        public Criteria andBuyerphoneNotLike(String value) {
            addCriterion("buyerPhone not like", value, "buyerphone");
            return (Criteria) this;
        }

        public Criteria andBuyerphoneIn(List<String> values) {
            addCriterion("buyerPhone in", values, "buyerphone");
            return (Criteria) this;
        }

        public Criteria andBuyerphoneNotIn(List<String> values) {
            addCriterion("buyerPhone not in", values, "buyerphone");
            return (Criteria) this;
        }

        public Criteria andBuyerphoneBetween(String value1, String value2) {
            addCriterion("buyerPhone between", value1, value2, "buyerphone");
            return (Criteria) this;
        }

        public Criteria andBuyerphoneNotBetween(String value1, String value2) {
            addCriterion("buyerPhone not between", value1, value2, "buyerphone");
            return (Criteria) this;
        }

        public Criteria andBuyerpasswordIsNull() {
            addCriterion("buyerPassword is null");
            return (Criteria) this;
        }

        public Criteria andBuyerpasswordIsNotNull() {
            addCriterion("buyerPassword is not null");
            return (Criteria) this;
        }

        public Criteria andBuyerpasswordEqualTo(String value) {
            addCriterion("buyerPassword =", value, "buyerpassword");
            return (Criteria) this;
        }

        public Criteria andBuyerpasswordNotEqualTo(String value) {
            addCriterion("buyerPassword <>", value, "buyerpassword");
            return (Criteria) this;
        }

        public Criteria andBuyerpasswordGreaterThan(String value) {
            addCriterion("buyerPassword >", value, "buyerpassword");
            return (Criteria) this;
        }

        public Criteria andBuyerpasswordGreaterThanOrEqualTo(String value) {
            addCriterion("buyerPassword >=", value, "buyerpassword");
            return (Criteria) this;
        }

        public Criteria andBuyerpasswordLessThan(String value) {
            addCriterion("buyerPassword <", value, "buyerpassword");
            return (Criteria) this;
        }

        public Criteria andBuyerpasswordLessThanOrEqualTo(String value) {
            addCriterion("buyerPassword <=", value, "buyerpassword");
            return (Criteria) this;
        }

        public Criteria andBuyerpasswordLike(String value) {
            addCriterion("buyerPassword like", value, "buyerpassword");
            return (Criteria) this;
        }

        public Criteria andBuyerpasswordNotLike(String value) {
            addCriterion("buyerPassword not like", value, "buyerpassword");
            return (Criteria) this;
        }

        public Criteria andBuyerpasswordIn(List<String> values) {
            addCriterion("buyerPassword in", values, "buyerpassword");
            return (Criteria) this;
        }

        public Criteria andBuyerpasswordNotIn(List<String> values) {
            addCriterion("buyerPassword not in", values, "buyerpassword");
            return (Criteria) this;
        }

        public Criteria andBuyerpasswordBetween(String value1, String value2) {
            addCriterion("buyerPassword between", value1, value2, "buyerpassword");
            return (Criteria) this;
        }

        public Criteria andBuyerpasswordNotBetween(String value1, String value2) {
            addCriterion("buyerPassword not between", value1, value2, "buyerpassword");
            return (Criteria) this;
        }

        public Criteria andBuyerstatusIsNull() {
            addCriterion("buyerStatus is null");
            return (Criteria) this;
        }

        public Criteria andBuyerstatusIsNotNull() {
            addCriterion("buyerStatus is not null");
            return (Criteria) this;
        }

        public Criteria andBuyerstatusEqualTo(Integer value) {
            addCriterion("buyerStatus =", value, "buyerstatus");
            return (Criteria) this;
        }

        public Criteria andBuyerstatusNotEqualTo(Integer value) {
            addCriterion("buyerStatus <>", value, "buyerstatus");
            return (Criteria) this;
        }

        public Criteria andBuyerstatusGreaterThan(Integer value) {
            addCriterion("buyerStatus >", value, "buyerstatus");
            return (Criteria) this;
        }

        public Criteria andBuyerstatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("buyerStatus >=", value, "buyerstatus");
            return (Criteria) this;
        }

        public Criteria andBuyerstatusLessThan(Integer value) {
            addCriterion("buyerStatus <", value, "buyerstatus");
            return (Criteria) this;
        }

        public Criteria andBuyerstatusLessThanOrEqualTo(Integer value) {
            addCriterion("buyerStatus <=", value, "buyerstatus");
            return (Criteria) this;
        }

        public Criteria andBuyerstatusIn(List<Integer> values) {
            addCriterion("buyerStatus in", values, "buyerstatus");
            return (Criteria) this;
        }

        public Criteria andBuyerstatusNotIn(List<Integer> values) {
            addCriterion("buyerStatus not in", values, "buyerstatus");
            return (Criteria) this;
        }

        public Criteria andBuyerstatusBetween(Integer value1, Integer value2) {
            addCriterion("buyerStatus between", value1, value2, "buyerstatus");
            return (Criteria) this;
        }

        public Criteria andBuyerstatusNotBetween(Integer value1, Integer value2) {
            addCriterion("buyerStatus not between", value1, value2, "buyerstatus");
            return (Criteria) this;
        }

        public Criteria andBuyerbalanceIsNull() {
            addCriterion("buyerBalance is null");
            return (Criteria) this;
        }

        public Criteria andBuyerbalanceIsNotNull() {
            addCriterion("buyerBalance is not null");
            return (Criteria) this;
        }

        public Criteria andBuyerbalanceEqualTo(Float value) {
            addCriterion("buyerBalance =", value, "buyerbalance");
            return (Criteria) this;
        }

        public Criteria andBuyerbalanceNotEqualTo(Float value) {
            addCriterion("buyerBalance <>", value, "buyerbalance");
            return (Criteria) this;
        }

        public Criteria andBuyerbalanceGreaterThan(Float value) {
            addCriterion("buyerBalance >", value, "buyerbalance");
            return (Criteria) this;
        }

        public Criteria andBuyerbalanceGreaterThanOrEqualTo(Float value) {
            addCriterion("buyerBalance >=", value, "buyerbalance");
            return (Criteria) this;
        }

        public Criteria andBuyerbalanceLessThan(Float value) {
            addCriterion("buyerBalance <", value, "buyerbalance");
            return (Criteria) this;
        }

        public Criteria andBuyerbalanceLessThanOrEqualTo(Float value) {
            addCriterion("buyerBalance <=", value, "buyerbalance");
            return (Criteria) this;
        }

        public Criteria andBuyerbalanceIn(List<Float> values) {
            addCriterion("buyerBalance in", values, "buyerbalance");
            return (Criteria) this;
        }

        public Criteria andBuyerbalanceNotIn(List<Float> values) {
            addCriterion("buyerBalance not in", values, "buyerbalance");
            return (Criteria) this;
        }

        public Criteria andBuyerbalanceBetween(Float value1, Float value2) {
            addCriterion("buyerBalance between", value1, value2, "buyerbalance");
            return (Criteria) this;
        }

        public Criteria andBuyerbalanceNotBetween(Float value1, Float value2) {
            addCriterion("buyerBalance not between", value1, value2, "buyerbalance");
            return (Criteria) this;
        }

        public Criteria andBuyeraccountIsNull() {
            addCriterion("buyerAccount is null");
            return (Criteria) this;
        }

        public Criteria andBuyeraccountIsNotNull() {
            addCriterion("buyerAccount is not null");
            return (Criteria) this;
        }

        public Criteria andBuyeraccountEqualTo(String value) {
            addCriterion("buyerAccount =", value, "buyeraccount");
            return (Criteria) this;
        }

        public Criteria andBuyeraccountNotEqualTo(String value) {
            addCriterion("buyerAccount <>", value, "buyeraccount");
            return (Criteria) this;
        }

        public Criteria andBuyeraccountGreaterThan(String value) {
            addCriterion("buyerAccount >", value, "buyeraccount");
            return (Criteria) this;
        }

        public Criteria andBuyeraccountGreaterThanOrEqualTo(String value) {
            addCriterion("buyerAccount >=", value, "buyeraccount");
            return (Criteria) this;
        }

        public Criteria andBuyeraccountLessThan(String value) {
            addCriterion("buyerAccount <", value, "buyeraccount");
            return (Criteria) this;
        }

        public Criteria andBuyeraccountLessThanOrEqualTo(String value) {
            addCriterion("buyerAccount <=", value, "buyeraccount");
            return (Criteria) this;
        }

        public Criteria andBuyeraccountLike(String value) {
            addCriterion("buyerAccount like", value, "buyeraccount");
            return (Criteria) this;
        }

        public Criteria andBuyeraccountNotLike(String value) {
            addCriterion("buyerAccount not like", value, "buyeraccount");
            return (Criteria) this;
        }

        public Criteria andBuyeraccountIn(List<String> values) {
            addCriterion("buyerAccount in", values, "buyeraccount");
            return (Criteria) this;
        }

        public Criteria andBuyeraccountNotIn(List<String> values) {
            addCriterion("buyerAccount not in", values, "buyeraccount");
            return (Criteria) this;
        }

        public Criteria andBuyeraccountBetween(String value1, String value2) {
            addCriterion("buyerAccount between", value1, value2, "buyeraccount");
            return (Criteria) this;
        }

        public Criteria andBuyeraccountNotBetween(String value1, String value2) {
            addCriterion("buyerAccount not between", value1, value2, "buyeraccount");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Buyer
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Buyer
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}