package com.ten.ParkNShop.entity;

public class Seller {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.sellerId
     *
     * @mbggenerated
     */
    private Integer sellerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.sellerName
     *
     * @mbggenerated
     */
    private String sellername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.shopName
     *
     * @mbggenerated
     */
    private String shopname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.sellerPassword
     *
     * @mbggenerated
     */
    private String sellerpassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.sellerEmail
     *
     * @mbggenerated
     */
    private String selleremail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.sellerPhone
     *
     * @mbggenerated
     */
    private String sellerphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.sellerBalance
     *
     * @mbggenerated
     */
    private Float sellerbalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.shopIntroduction
     *
     * @mbggenerated
     */
    private String shopintroduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.shopStatus
     *
     * @mbggenerated
     */
    private Integer shopstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.sellerId
     *
     * @return the value of seller.sellerId
     *
     * @mbggenerated
     */
    public Integer getSellerid() {
        return sellerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.sellerId
     *
     * @param sellerid the value for seller.sellerId
     *
     * @mbggenerated
     */
    public void setSellerid(Integer sellerid) {
        this.sellerid = sellerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.sellerName
     *
     * @return the value of seller.sellerName
     *
     * @mbggenerated
     */
    public String getSellername() {
        return sellername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.sellerName
     *
     * @param sellername the value for seller.sellerName
     *
     * @mbggenerated
     */
    public void setSellername(String sellername) {
        this.sellername = sellername == null ? null : sellername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.shopName
     *
     * @return the value of seller.shopName
     *
     * @mbggenerated
     */
    public String getShopname() {
        return shopname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.shopName
     *
     * @param shopname the value for seller.shopName
     *
     * @mbggenerated
     */
    public void setShopname(String shopname) {
        this.shopname = shopname == null ? null : shopname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.sellerPassword
     *
     * @return the value of seller.sellerPassword
     *
     * @mbggenerated
     */
    public String getSellerpassword() {
        return sellerpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.sellerPassword
     *
     * @param sellerpassword the value for seller.sellerPassword
     *
     * @mbggenerated
     */
    public void setSellerpassword(String sellerpassword) {
        this.sellerpassword = sellerpassword == null ? null : sellerpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.sellerEmail
     *
     * @return the value of seller.sellerEmail
     *
     * @mbggenerated
     */
    public String getSelleremail() {
        return selleremail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.sellerEmail
     *
     * @param selleremail the value for seller.sellerEmail
     *
     * @mbggenerated
     */
    public void setSelleremail(String selleremail) {
        this.selleremail = selleremail == null ? null : selleremail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.sellerPhone
     *
     * @return the value of seller.sellerPhone
     *
     * @mbggenerated
     */
    public String getSellerphone() {
        return sellerphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.sellerPhone
     *
     * @param sellerphone the value for seller.sellerPhone
     *
     * @mbggenerated
     */
    public void setSellerphone(String sellerphone) {
        this.sellerphone = sellerphone == null ? null : sellerphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.sellerBalance
     *
     * @return the value of seller.sellerBalance
     *
     * @mbggenerated
     */
    public Float getSellerbalance() {
        return sellerbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.sellerBalance
     *
     * @param sellerbalance the value for seller.sellerBalance
     *
     * @mbggenerated
     */
    public void setSellerbalance(Float sellerbalance) {
        this.sellerbalance = sellerbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.shopIntroduction
     *
     * @return the value of seller.shopIntroduction
     *
     * @mbggenerated
     */
    public String getShopintroduction() {
        return shopintroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.shopIntroduction
     *
     * @param shopintroduction the value for seller.shopIntroduction
     *
     * @mbggenerated
     */
    public void setShopintroduction(String shopintroduction) {
        this.shopintroduction = shopintroduction == null ? null : shopintroduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.shopStatus
     *
     * @return the value of seller.shopStatus
     *
     * @mbggenerated
     */
    public Integer getShopstatus() {
        return shopstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.shopStatus
     *
     * @param shopstatus the value for seller.shopStatus
     *
     * @mbggenerated
     */
    public void setShopstatus(Integer shopstatus) {
        this.shopstatus = shopstatus;
    }

    @Override
    public String toString() {
        return "Seller{" +
                "sellerid=" + sellerid +
                ", sellername='" + sellername + '\'' +
                ", shopname='" + shopname + '\'' +
                ", sellerpassword='" + sellerpassword + '\'' +
                ", selleremail='" + selleremail + '\'' +
                ", sellerphone='" + sellerphone + '\'' +
                ", sellerbalance=" + sellerbalance +
                ", shopintroduction='" + shopintroduction + '\'' +
                ", shopstatus=" + shopstatus +
                '}';
    }
}